- name: systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart hive
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - hive-metastore
    - hiveserver2
  failed_when: false
