hadoop_user: hadoop
hadoop_group: hadoop

yarn_user: yarn
yarn_group: yarn

hadoop_conf_dir: /etc/hadoop/conf

hadoop_packages:
  - openjdk-8-jdk
  - hadoop
  - hadoop-hdfs
  - hadoop-yarn
  - hadoop-mapreduce

hadoop_var_root: /var/lib/hadoop
hadoop_tmp_dir: /var/lib/hadoop/tmp
yarn_local_dir: /var/lib/hadoop/yarn/local
yarn_log_dir: /var/lib/hadoop/yarn/logs

hdfs_workdir: /var/lib/hadoop-hdfs
yarn_workdir: /var/lib/hadoop-yarn

fs_defaultfs: "hdfs://localhost:9000"
rm_hostname: "localhost"
yarn_rm_webapp: "0.0.0.0:8088"

yarn_nm_memory_mb: 1024
yarn_sched_max_mb: 1024
yarn_sched_min_mb: 128

ats_enabled: true
ats_version: "2.0"
ats_hostname: "localhost"
ats_address: "0.0.0.0:10200"
ats_api: "0.0.0.0:8188"
atsv2_dir: /atsv2

yarn_log_aggregation: true
yarn_remote_app_log_dir: "/app-logs"
yarn_log_server_url: "http://0.0.0.0:19888/jobhistory/logs"

jhs_rpc: "localhost:10020"
jhs_webapp: "0.0.0.0:19888"
jhs_done_dir: "/mr-history/done"
jhs_intermediate_dir: "/mr-history/tmp"
