- name: apt update cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install Java 11
  ansible.builtin.apt:
    name: "{{ zeppelin_java_package }}"
    state: present
